#ifndef CONFIG_SDKCONFIG_H_
#define CONFIG_SDKCONFIG_H_

#define CONFIG_BLUEPAD32_PLATFORM_CUSTOM
#define CONFIG_TARGET_PICO_W
#define CONFIG_BLUEPAD32_LOG_LEVEL 0  // INFO

#define CONFIG_BLUEPAD32_MAX_DEVICES 1
#define CONFIG_BLUEPAD32_MAX_ALLOWLIST 1
#define CONFIG_BLUEPAD32_GAP_SECURITY 1
#define CONFIG_BLUEPAD32_ENABLE_BLE_BY_DEFAULT 1

#endif  // CONFIG_SDKCONFIG_H_